<?php
/*
 * FalconideAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FalconideAPIV10Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Emailv1 implements JsonSerializable
{
    /**
     * Your secret API Key
     * @maps api_key
     * @var string|null $apiKey public property
     */
    public $apiKey;

    /**
     * @todo Write general description for this property
     * @maps email_details
     * @var EmailDetails|null $emailDetails public property
     */
    public $emailDetails;

    /**
     * @todo Write general description for this property
     * @maps X-APIHEADER
     * @var array|null $xAPIHEADER public property
     */
    public $xAPIHEADER;

    /**
     * @todo Write general description for this property
     * @var Settings|null $settings public property
     */
    public $settings;

    /**
     * @todo Write general description for this property
     * @var array|null $recipients public property
     */
    public $recipients;

    /**
     * @todo Write general description for this property
     * @var Attributes|null $attributes public property
     */
    public $attributes;

    /**
     * @todo Write general description for this property
     * @var Files|null $files public property
     */
    public $files;

    /**
     * Constructor to set initial or default values of member properties
     * @param string       $apiKey       Initialization value for $this->apiKey
     * @param EmailDetails $emailDetails Initialization value for $this->emailDetails
     * @param array        $xAPIHEADER   Initialization value for $this->xAPIHEADER
     * @param Settings     $settings     Initialization value for $this->settings
     * @param array        $recipients   Initialization value for $this->recipients
     * @param Attributes   $attributes   Initialization value for $this->attributes
     * @param Files        $files        Initialization value for $this->files
     */
    public function __construct()
    {
        if (7 == func_num_args()) {
            $this->apiKey       = func_get_arg(0);
            $this->emailDetails = func_get_arg(1);
            $this->xAPIHEADER   = func_get_arg(2);
            $this->settings     = func_get_arg(3);
            $this->recipients   = func_get_arg(4);
            $this->attributes   = func_get_arg(5);
            $this->files        = func_get_arg(6);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['api_key']       = $this->apiKey;
        $json['email_details'] = $this->emailDetails;
        $json['X-APIHEADER']   = $this->xAPIHEADER;
        $json['settings']      = $this->settings;
        $json['recipients']    = $this->recipients;
        $json['attributes']    = $this->attributes;
        $json['files']         = $this->files;

        return $json;
    }
}
