<?php
/*
 * FalconideAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FalconideAPIV10Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Files implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @maps example_attachment1.txt
     * @var string|null $exampleAttachment1Txt public property
     */
    public $exampleAttachment1Txt;

    /**
     * @todo Write general description for this property
     * @maps example_attachment2.txt
     * @var string|null $exampleAttachment2Txt public property
     */
    public $exampleAttachment2Txt;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $exampleAttachment1Txt Initialization value for $this->exampleAttachment1Txt
     * @param string $exampleAttachment2Txt Initialization value for $this->exampleAttachment2Txt
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->exampleAttachment1Txt = func_get_arg(0);
            $this->exampleAttachment2Txt = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['example_attachment1.txt'] = $this->exampleAttachment1Txt;
        $json['example_attachment2.txt'] = $this->exampleAttachment2Txt;

        return $json;
    }
}
