<?php
/*
 * FalconideAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FalconideAPIV10Lib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Settings implements JsonSerializable
{
    /**
     * @todo Write general description for this property
     * @var bool|null $footer public property
     */
    public $footer;

    /**
     * @todo Write general description for this property
     * @var bool|null $clicktrack public property
     */
    public $clicktrack;

    /**
     * @todo Write general description for this property
     * @var bool|null $opentrack public property
     */
    public $opentrack;

    /**
     * @todo Write general description for this property
     * @var bool|null $unsubscribe public property
     */
    public $unsubscribe;

    /**
     * @todo Write general description for this property
     * @var string|null $bcc public property
     */
    public $bcc;

    /**
     * @todo Write general description for this property
     * @var string|null $attachmentid public property
     */
    public $attachmentid;

    /**
     * @todo Write general description for this property
     * @var integer|null $template public property
     */
    public $template;

    /**
     * Constructor to set initial or default values of member properties
     * @param bool    $footer       Initialization value for $this->footer
     * @param bool    $clicktrack   Initialization value for $this->clicktrack
     * @param bool    $opentrack    Initialization value for $this->opentrack
     * @param bool    $unsubscribe  Initialization value for $this->unsubscribe
     * @param string  $bcc          Initialization value for $this->bcc
     * @param string  $attachmentid Initialization value for $this->attachmentid
     * @param integer $template     Initialization value for $this->template
     */
    public function __construct()
    {
        switch (func_num_args()) {
            case 7:
                $this->footer       = func_get_arg(0);
                $this->clicktrack   = func_get_arg(1);
                $this->opentrack    = func_get_arg(2);
                $this->unsubscribe  = func_get_arg(3);
                $this->bcc          = func_get_arg(4);
                $this->attachmentid = func_get_arg(5);
                $this->template     = func_get_arg(6);
                break;

            default:
                $this->footer = true;
                $this->clicktrack = true;
                $this->opentrack = true;
                $this->unsubscribe = true;
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['footer']       = $this->footer;
        $json['clicktrack']   = $this->clicktrack;
        $json['opentrack']    = $this->opentrack;
        $json['unsubscribe']  = $this->unsubscribe;
        $json['bcc']          = $this->bcc;
        $json['attachmentid'] = $this->attachmentid;
        $json['template']     = $this->template;

        return $json;
    }
}
