<?php
/*
 * FalconideAPIV10Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace FalconideAPIV10Lib;

use FalconideAPIV10Lib\Controllers;

/**
 * FalconideAPIV10Lib client class
 */
class FalconideAPIV10Client
{
    /**
     * Singleton access to Email controller
     * @return Controllers\EmailController The *Singleton* instance
     */
    public function getEmail()
    {
        return Controllers\EmailController::getInstance();
    }
}
